{"name": "Проверка неуспешного логина для существующего курьера - неверный логин", "status": "passed", "start": 1730235331562, "stop": 1730235331625, "uuid": "e442919d-b1ee-451a-84ad-41694ea65fe4", "historyId": "30baf53ae4ef43a401e3e7be220c8519", "testCaseId": "30baf53ae4ef43a401e3e7be220c8519", "fullName": "tests.test_login_courier.TestLoginCourier#test_courier_cant_login_with_wrong_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "home"}, {"name": "thread", "value": "15252-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}